// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Via } from "./Via";

/**
 * 地址栏那一行的解析结果。
 *
 * 后端**解析到底**：哪篇笔记、哪一版、还是不存在。前端只按 `kind` 分发 ——
 * 加新语法时在这里加变体，界面补一个分支即可。
 *
 * 返回的 `title` / `short_id` 都是**规范全称**，界面直接拿来回显地址栏
 * （所以用 `@缩写` 跳转之后，地址栏会显示成 `名称@缩写`）。
 *
 * **判别式只有这一处定义**：TypeScript 那一侧由 `ts-rs` 从这里导出
 * （`cargo test` 会写进 `src/bindings/`），前端不再手写第二份 —— 手写的那份已经漂移过。
 */
export type Address = { "kind": "empty" } | { "kind": "note", title: string, address: string, 
/**
 * 是通过哪条指令来到这一页的（直接打开时为 `null`）
 */
via: Via | null, 
/**
 * 指令页面 + `@no-command`：正文要包成**代码块**显示（不执行指令）
 */
code_block: boolean, } | { "kind": "edit", title: string, address: string, } | { "kind": "history", title: string, address: string, } | { "kind": "delete", title: string, address: string, } | { "kind": "view-version", title: string, 
/**
 * 版本号：远小于 2^53，前端按普通数字处理即可（默认会导成 bigint，用不了）
 */
rev: number, id: string, short_id: string, address: string, } | { "kind": "rollback-confirm", title: string, 
/**
 * 版本号：远小于 2^53，前端按普通数字处理即可（默认会导成 bigint，用不了）
 */
rev: number, id: string, short_id: string, address: string, } | { "kind": "special", page: string, address: string, 
/**
 * 是通过哪条指令来到这一页的（直接打开时为 `null`）。
 * 虚拟命名空间下的页面同样要能看到来源 —— 它就是普通页面的一种。
 */
via: Via | null, } | { "kind": "missing", title: string, address: string, };
