// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 是通过哪条指令来到这一页的（跟过重定向的阅读路径会带上）。
 */
export type Via = { 
/**
 * 来源页面标题；随机跳转时它是**发起随机的页面**，不是目标
 */
from: string, 
/**
 * 是否随机跳转：提示语据此写成"来自随机重定向"
 */
random: boolean, };
